version: "3.8"
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com # Replace with your email address
      PGADMIN_DEFAULT_PASSWORD: admin # Replace with a secure password
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  postgres_data:
